//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PuntoVentaProyectoFinalEntities : DbContext
    {
        public PuntoVentaProyectoFinalEntities()
            : base("name=PuntoVentaProyectoFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoriaProductos> categoriaProductos { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<detalle_ventas> detalle_ventas { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<ventas> ventas { get; set; }
    
        public virtual int agregarClientes(string nombre, string apellido, string direccion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("agregarClientes", nombreParameter, apellidoParameter, direccionParameter);
        }
    
        public virtual int agregarProductos(string nombre, Nullable<int> stock, Nullable<double> precioProducto, Nullable<int> idCategoria)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("stock", stock) :
                new ObjectParameter("stock", typeof(int));
    
            var precioProductoParameter = precioProducto.HasValue ?
                new ObjectParameter("precioProducto", precioProducto) :
                new ObjectParameter("precioProducto", typeof(double));
    
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("idCategoria", idCategoria) :
                new ObjectParameter("idCategoria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("agregarProductos", nombreParameter, stockParameter, precioProductoParameter, idCategoriaParameter);
        }
    
        public virtual int agregarVentaProducto(Nullable<int> idventa, Nullable<int> idproducto, Nullable<int> canti, Nullable<double> precio)
        {
            var idventaParameter = idventa.HasValue ?
                new ObjectParameter("idventa", idventa) :
                new ObjectParameter("idventa", typeof(int));
    
            var idproductoParameter = idproducto.HasValue ?
                new ObjectParameter("idproducto", idproducto) :
                new ObjectParameter("idproducto", typeof(int));
    
            var cantiParameter = canti.HasValue ?
                new ObjectParameter("canti", canti) :
                new ObjectParameter("canti", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("agregarVentaProducto", idventaParameter, idproductoParameter, cantiParameter, precioParameter);
        }
    
        public virtual int crearCategorias(string nombreCategoria)
        {
            var nombreCategoriaParameter = nombreCategoria != null ?
                new ObjectParameter("nombreCategoria", nombreCategoria) :
                new ObjectParameter("nombreCategoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crearCategorias", nombreCategoriaParameter);
        }
    
        public virtual int crearUsuarios(string usuario, string nombre, string apellido, string pass)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crearUsuarios", usuarioParameter, nombreParameter, apellidoParameter, passParameter);
        }
    
        public virtual int editarCategorias(Nullable<int> id, string nombreCategoria)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreCategoriaParameter = nombreCategoria != null ?
                new ObjectParameter("nombreCategoria", nombreCategoria) :
                new ObjectParameter("nombreCategoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editarCategorias", idParameter, nombreCategoriaParameter);
        }
    
        public virtual int editarClientes(Nullable<int> idcliente, string nombre, string apellido, string direccion)
        {
            var idclienteParameter = idcliente.HasValue ?
                new ObjectParameter("idcliente", idcliente) :
                new ObjectParameter("idcliente", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editarClientes", idclienteParameter, nombreParameter, apellidoParameter, direccionParameter);
        }
    
        public virtual int editarProductos(Nullable<int> id, string nombre, Nullable<int> stock, Nullable<double> precioProducto, Nullable<int> idCategoria)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("stock", stock) :
                new ObjectParameter("stock", typeof(int));
    
            var precioProductoParameter = precioProducto.HasValue ?
                new ObjectParameter("precioProducto", precioProducto) :
                new ObjectParameter("precioProducto", typeof(double));
    
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("idCategoria", idCategoria) :
                new ObjectParameter("idCategoria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editarProductos", idParameter, nombreParameter, stockParameter, precioProductoParameter, idCategoriaParameter);
        }
    
        public virtual int editarUsuarios(Nullable<int> id, string usuario, string nombre, string apellido, string pass)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editarUsuarios", idParameter, usuarioParameter, nombreParameter, apellidoParameter, passParameter);
        }
    
        public virtual ObjectResult<sp_DetalleVenta_Result> sp_DetalleVenta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DetalleVenta_Result>("sp_DetalleVenta");
        }
    
        public virtual ObjectResult<sp_DetalleVentaFiltrada_Result> sp_DetalleVentaFiltrada(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DetalleVentaFiltrada_Result>("sp_DetalleVentaFiltrada", nombreParameter);
        }
    
        public virtual ObjectResult<sp_DetalleVenta1_Result> sp_DetalleVenta1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DetalleVenta1_Result>("sp_DetalleVenta1");
        }
    
        public virtual ObjectResult<imprimirFactura_Result> imprimirFactura(Nullable<int> idVenta)
        {
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<imprimirFactura_Result>("imprimirFactura", idVentaParameter);
        }
    
        public virtual ObjectResult<reporteINventario_Result> reporteINventario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<reporteINventario_Result>("reporteINventario");
        }
    
        public virtual ObjectResult<reporteProductosMasVendidos_Result> reporteProductosMasVendidos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<reporteProductosMasVendidos_Result>("reporteProductosMasVendidos");
        }
    
        public virtual ObjectResult<reporteINventario1_Result> reporteINventario1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<reporteINventario1_Result>("reporteINventario1");
        }
    
        public virtual ObjectResult<reporteProductosMasVendidos1_Result> reporteProductosMasVendidos1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<reporteProductosMasVendidos1_Result>("reporteProductosMasVendidos1");
        }
    
        public virtual ObjectResult<reporteINventario2_Result> reporteINventario2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<reporteINventario2_Result>("reporteINventario2");
        }
    
        public virtual ObjectResult<reporteProductosMasVendidos2_Result> reporteProductosMasVendidos2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<reporteProductosMasVendidos2_Result>("reporteProductosMasVendidos2");
        }
    
        public virtual ObjectResult<Nullable<decimal>> reporteInicioVenta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("reporteInicioVenta");
        }
    
        public virtual ObjectResult<Nullable<decimal>> reporteInicioIventario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("reporteInicioIventario");
        }
    }
}
